const char* indexHtml =
    "<!DOCTYPE html>"
    "<html lang='en'>"
    "<head>"
    "<meta charset='UTF-8'>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<title>Atualizar FirmWare</title>"
    "<style>"
    "body {"
    "    font-family: Verdana, sans-serif;"
    "    font-size: 16px;"
    "    margin: 0;"
    "    padding: 0;"
    "    display: flex;"
    "    justify-content: center;"
    "    align-items: center;"
    "    height: 100vh;"
    "    background-color: #f5f5f5;"
    "}"
    "div.container {"
    "    width: 100%;"
    "    max-width: 500px;"
    "    padding: 20px;"
    "    border-radius: 10px;"
    "    border: solid 2px #e0e0e0;"
    "    background-color: white;"
    "    box-shadow: 0 4px 10px rgba(0,0,0,0.1);"
    "}"
    "h1 {"
    "    text-align: center;"
    "    font-size: 22px;"
    "    font-weight: bold;"
    "    margin-bottom: 20px;"
    "}"
    "form {"
    "    display: flex;"
    "    flex-direction: column;"
    "    gap: 10px;"
    "}"
    "input[type='file'] {"
    "    padding: 12px;"
    "    font-size: 16px;"
    "    border: 1px solid #ccc;"
    "    border-radius: 5px;"
    "    width: 100%;"
    "}"
    "input[type='submit'] {"
    "    padding: 12px;"
    "    font-size: 16px;"
    "    background-color: #2196F3;"
    "    color: white;"
    "    border: none;"
    "    border-radius: 5px;"
    "    cursor: pointer;"
    "}"
    "input[type='submit']:hover {"
    "    background-color: #0b7dda;"
    "}"
    "#error-message {"
    "    color: red;"
    "    font-size: 14px;"
    "    margin-bottom: 15px;"
    "    text-align: center;"
    "}"
    "#prg-container {"
    "    width: 100%;"
    "    background-color: #e0e0e0;"
    "    border-radius: 8px;"
    "    overflow: hidden;"
    "    margin-top: 20px;"
    "}"
    "#prg {"
    "    width: 0%;"
    "    background-color: #2196F3;"
    "    padding: 5px;"
    "    text-align: center;"
    "    color: white;"
    "    font-weight: bold;"
    "}"
    "@media only screen and (max-width: 600px) {"
    "    h1 { font-size: 20px; }"
    "    input[type='file'], input[type='submit'] {"
    "        font-size: 18px;"
    "    }"
    "    body {"
    "        padding: 10px;"
    "    }"
    "}"
    "</style>"
    "</head>"
    "<body>"
    "<div class='container'>"
    "<h1>Atualizar FirmWare</h1>"
    "<form method='POST' action='#' enctype='multipart/form-data' id='upload-form'>"
    "<input type='file' name='update' id='file-input'>"
    "<input type='submit' value='Update'>"
    "</form>"
    "<div id='error-message'></div>"
    "<div id='prg-container'>"
    "<div id='prg'>0%</div>"
    "</div>"
    "</div>"
    "<script>"
    "var prg = document.getElementById('prg');"
    "var form = document.getElementById('upload-form');"
    "var errorMsg = document.getElementById('error-message');"
    "form.addEventListener('submit', e => {"
        "e.preventDefault();"
        "errorMsg.innerHTML = '';"
        "var fileInput = document.getElementById('file-input');"
        "var file = fileInput.files[0];"
        "if (!file) {"
            "errorMsg.innerHTML = 'Por favor, selecione um arquivo.';"
            "return;"
        "}"
        "var fileName = file.name;"
        "if (!fileName.endsWith('.bin')) {"
            "errorMsg.innerHTML = 'O arquivo deve ser um .bin';"
            "return;"
        "}"
        "if (!fileName.startsWith('firmware_B')) {"
            "errorMsg.innerHTML = 'Arquivo invalido';"
            "return;"
        "}"
        "var data = new FormData(form);"
        "var req = new XMLHttpRequest();"
        "req.open('POST', '/update');"
        "req.upload.addEventListener('progress', p => {"
            "if (p.lengthComputable) {"
                "let w = Math.round((p.loaded / p.total) * 100) + '%';"
                "prg.innerHTML = w;"
                "prg.style.width = w;"
                "if (w === '100%') prg.style.backgroundColor = '#04AA6D';"
            "}"
        "});"
        "req.send(data);"
    "});"
    "</script>"
    "</body>"
    "</html>";
